[package]
name = "lvl-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lvl-math = { path = "../lvl-math" }
pollster = "0.3"
thiserror = "1"
wgpu = "0.19"
winit = "0.29"
