[package]
name = "lvl-resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lvl-math = { path = "../lvl-math" }
serde = { version = "1", features = ["derive"] }
